### ISSUE TITLE
ObjectId Type Mismatch in MongoDB $match Stage

### ISSUE THREAD

**Issue by marvillage** [avantifellows/reporting#56]
On the website, when trying to retrieve quiz stats by date, no data is shown. This is caused by the backend incorrectly matching the _id field (ObjectId) as a string in the database query, preventing any relevant documents from being found.

**Comment by suryabulusu** [comment]
Hey -- we use reporting mostly via parameterized URLs. 

Check this: https://reports.avantifellows.org/reports/live_session_report/PunjabStudents_6642112317f06c9050c70739
